package org.gdou.model;

import java.io.Serializable;

public class Oauths implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauths.id
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauths.user_id
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauths.oauth_type
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    private String oauthType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauths.oauth_id
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    private String oauthId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauths.unionid
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    private String unionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauths.credential
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    private String credential;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauths
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauths.id
     *
     * @return the value of oauths.id
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauths.id
     *
     * @param id the value for oauths.id
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauths.user_id
     *
     * @return the value of oauths.user_id
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauths.user_id
     *
     * @param userId the value for oauths.user_id
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauths.oauth_type
     *
     * @return the value of oauths.oauth_type
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    public String getOauthType() {
        return oauthType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauths.oauth_type
     *
     * @param oauthType the value for oauths.oauth_type
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    public void setOauthType(String oauthType) {
        this.oauthType = oauthType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauths.oauth_id
     *
     * @return the value of oauths.oauth_id
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    public String getOauthId() {
        return oauthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauths.oauth_id
     *
     * @param oauthId the value for oauths.oauth_id
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    public void setOauthId(String oauthId) {
        this.oauthId = oauthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauths.unionid
     *
     * @return the value of oauths.unionid
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauths.unionid
     *
     * @param unionid the value for oauths.unionid
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauths.credential
     *
     * @return the value of oauths.credential
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    public String getCredential() {
        return credential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauths.credential
     *
     * @param credential the value for oauths.credential
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    public void setCredential(String credential) {
        this.credential = credential;
    }
}