package org.gdou.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.gdou.model.Oauths;
import org.gdou.model.OauthsExample;

public interface OauthsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauths
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    long countByExample(OauthsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauths
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    int deleteByExample(OauthsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauths
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauths
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    int insert(Oauths record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauths
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    int insertSelective(Oauths record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauths
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    List<Oauths> selectByExample(OauthsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauths
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    Oauths selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauths
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Oauths record, @Param("example") OauthsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauths
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Oauths record, @Param("example") OauthsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauths
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Oauths record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauths
     *
     * @mbg.generated Sun Mar 01 15:28:59 GMT+08:00 2020
     */
    int updateByPrimaryKey(Oauths record);
}