server:
  # 端口号
  port: 80
log:
  level: info

user:
  interceptor: true

#es连接
elasticsearch:
  host: 18.163.180.46
  port: 9200
  password: ENC(SyEoGEBiQqcIIEzbLq8oHkrroNJfS53cLHJHDWkUKZLJONPjmXMGwOpeVDI0caxa)

#redis相关
spring:
  redis:
    host: 18.163.180.46
    password: ENC(SyEoGEBiQqcIIEzbLq8oHkrroNJfS53cLHJHDWkUKZLJONPjmXMGwOpeVDI0caxa)
    jedis:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 4
        min-idle: 0
    timeout: 5000