spring:
  profiles:
    active: master
  main:
    allow-bean-definition-overriding: true


  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.13.98.231:3310/PsySystem?serverTimezone=CTT
    username: hill
    password: ENC(SyEoGEBiQqcIIEzbLq8oHkrroNJfS53cLHJHDWkUKZLJONPjmXMGwOpeVDI0caxa)

    # Druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化
    initialSize: 3
    # 最大
    maxActive: 20
    # 最小
    minIdle: 3
    # 最大连接等待超时时间
    maxWait: 60000
    # 打开PSCache,并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间,单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  http:
    # 过滤字符编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true


mybatis:
  type-aliases-package: org.gdou.model.po
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

baidu:
  bos:
    ACCESS_KEY_ID: ENC(ctriaRinKcSkjln9kAlCSlglYUaF9D1e5GWIoXkGBwET8hzLwDXeuqxEnZcpWU26cUvhQZXfVjR6Z/N8tgXrOJs0HR4tbih9FzTbOPIs1pQ=)
    SECRET_ACCESS_KEY: ENC(HYFwbWPS1RArXEPJOOeFmu5i5Xj3NTf34W5q1+DbZrD/Sxs9SEsEUz2he+lISwgSP1lymYG3NThUtaHNiWpOTDNZSwDpjdkSmeHAg6IwSec=)
